"""sync models with database

Revision ID: e3deb3c840b5
Revises: 9cb446cd341c
Create Date: 2026-09-01 03:32:44.326805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3deb3c840b5'
down_revision = '9cb446cd341c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('request_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_foreign_key(
    "fk_borrowing_requests_user_id",
    "users",
    ["user_id"],
    ["id"]
)

        batch_op.create_foreign_key("fk_borrowing_requests_equipment_id", "items",
        ["equipment_id"],
        ["id"]
)
        batch_op.drop_constraint(
    "fk_borrowing_requests_user_id",
    type_="foreignkey"
)

    batch_op.drop_constraint(
    "fk_borrowing_requests_equipment_id",
    type_="foreignkey"
)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('borrowing_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('message')
        batch_op.drop_column('request_date')
        batch_op.drop_column('equipment_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
